[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
